name: oncampus
recipe: lemp
config:
  webroot: public

services:
  appserver:
    config:
      vhosts: lando/nginx.conf
      php: lando/php.ini
      database: lando/mysql.conf
  node:
    type: node:13

  database:
    portforward: 3313
    creds:
      user: oncampus
      password: oncampus
      database: oncampus

tooling:
  console:
    service: appserver
    cmd: bin/console
  yarn:
    service: node

# lando composer create-project symfony/website-skeleton tmp && cp -r tmp/. . && rm -rf tmp